sudo: required
services:
  - docker

before_install:
  - docker build -t ramsinghcg/react-test -f ./client/Dockerfile.dev ./client
  # react-test --> image name, it can be anything, but ramsinghcg(docker id) name should be in small letter
  # ./client   ---> build context

script:
  - docker run ramsinghcg/react-test npm test -- --coverage

after_success:
  - docker build -t ramsinghcg/multi-client ./client
  - docker build -t ramsinghcg/multi-nginx ./nginx
  - docker build -t ramsinghcg/multi-server ./server
  - docker build -t ramsinghcg/multi-worker ./worker
  # Log in to the docker CLI, my docker id = ramsinghcg
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ramsinghcg/multi-client
  - docker push ramsinghcg/multi-nginx
  - docker push ramsinghcg/multi-server
  - docker push ramsinghcg/multi-worker
deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-528716534830
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY