sudo: required
services:
  - docker

before_install:
  - docker build -t RamSinghAKG/react-test -f ./client/Dockerfile.dev ./client
  # RamSinghAKG/react-test --> image name, it can be anything
  # ./client   ---> build context

script:
  - docker run RamSinghAKG/react-test npm test -- --coverage

after_success:
  - docker build -t stephengrider/multi-client ./client
  - docker build -t stephengrider/multi-nginx ./nginx
  - docker build -t stephengrider/multi-server ./server
  - docker build -t stephengrider/multi-worker ./worker
  # Log in to the docker CLI
  - echo "#DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push RamSinghAKG/multi-client
  - docker push RamSinghAKG/multi-nginx
  - docker push RamSinghAKG/multi-server
  - docker push RamSinghAKG/multi-worker